import { attribute, autoGeneratedHashKey, table } from "@aws/dynamodb-data-mapper-annotations";

const todosTable = process.env.todosTable || "";

@table(todosTable)
export class ToDoModel {

  @autoGeneratedHashKey()
  public id!: string;

  @attribute()
  public createdAt!: string;

  @attribute()
  public updatedAt!: string;

  @attribute()
  public text!: string;

  @attribute()
  public duedate!: string;

}
